// This file contains the REST API request definitions for the server.
GET http://localhost:4000/api/customers
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijgydmk4anpvbzVCY3h3YnNnMEZHNyJ9.eyJpc3MiOiJodHRwczovL2Rldi1kYW0xank3bTdiYWFtcXNoLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2ODRiNDk0ZjE5MjUyODI5YzY1Y2U2YjEiLCJhdWQiOlsiY2FydmVkcm9ja2FwaS5henVyZXdlYnNpdGVzLm5ldCIsImh0dHBzOi8vZGV2LWRhbTFqeTdtN2JhYW1xc2gudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTc0OTc2ODQxNiwiZXhwIjoxNzQ5NzY4NzE2LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIHJlYWQ6Y3VzdG9tZXJzLXNpbmdsZSByZWFkOm9yZGVycy1zaW5nbGUgd3JpdGU6Y3VzdG9tZXJzIiwiYXpwIjoiVzJwSmFQS0V0RWpiQjJCN3drT20wVTVTQUFlTnlNbkYifQ.pIEMwNI_KEIsiyJQljtlFxH1XA4WW9PmaHWWcA8dn23cIh8fPAm9naVPpUhkFzJqWrEo_KMSrQCYc6HrZ0uMUU_rvB_PmsL26H4L8O1m9lvwtRQLmGo4G17Rt9cyzarzzrD9h2CH4f7ElFVenVyayrkG0ZCTGEamE9woKdbJktZV1v5jo6Wbj14s_-FE1W3UT_794zXQnR8EL52Y09p876daAPl-TS8hwLR6GiS5zEWKFVz6L-8nLhixnipv2eLiXqtPurgzxPcO3aLPmLMKWvfzz8gh0H3J8krnzFS96qWS_U1VbGi2TIK6BKWagEIegjLDVK-T6QzDKYeFkHThog
